on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      name:
        required: true
        type: string
      tag:
        required: true
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      use_submodule_ssh:
        required: false
        type: boolean
        default: false
    secrets:
      SUBMODULE_SSH_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    env:
      IMAGE_NAME: ${{ vars.REGISTRY_URL }}/${{ inputs.name }}
      IMAGE_TAG: ${{ inputs.tag }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup submodules
      if: ${{ inputs.use_submodule_ssh }}
      env:
        SSH_KEY: ${{ secrets.SUBMODULE_SSH_KEY }}
      run: |
        set -euox pipefail

        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        git submodule update --init --recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.dockerfile }}
        push: false # GCP credentials are short-lived (5 minutes), so we can't init creds first, have possibly >5 min build, and then push using those creds
        load: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - id: auth
      name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        project_id: '${{ vars.PROJECT_ID }}'
        workload_identity_provider: '${{ vars.WORKLOAD_IDENTITY_PROVIDER }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

    - name: Push image
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_NAME }}:latest