on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      containers:
        required: true
        type: object

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    env:
      IMAGE_NAME: ${{ vars.REGISTRY_URL }}/${{ inputs.name }}
      IMAGE_TAG: ${{ inputs.tag }}

    steps:
    - id: auth
      name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        project_id: '${{ vars.PROJECT_ID }}'
        workload_identity_provider: '${{ vars.WORKLOAD_IDENTITY_PROVIDER }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ vars.GKE_CLUSTER }}

    - name: Rollout new image
      run: |
        CONTAINERS='${{ toJSON(inputs.containers) }}'
        UPDATES=""
        for KEY in $(echo "$CONTAINERS" | jq -r 'keys[]'); do
          VALUE=$(echo "$CONTAINERS" | jq -r ".[\"$KEY\"]")
          UPDATES="$UPDATES $KEY=${{ vars.REGISTRY_URL }}/$VALUE"
        done

        echo "Image updates are the following: $UPDATES"
        kubectl set image -n ${{ vars.NAMESPACE }} ${{ vars.RESOURCE_TYPE }}/${{ vars.RESOURCE_NAME }} $UPDATES

    - name: Wait for rollout
      run: |
        kubectl rollout status -n ${{ vars.NAMESPACE }} ${{ vars.RESOURCE_TYPE }}/${{ vars.RESOURCE_NAME }} --timeout=120s